### PR TITLE
Replace picosanity with full client

### PR DESCRIPTION
**Pull request by kmelve**
This PR replaces the picosanity client with the full client. This lets users of `next-sanity` to use the built-in client for mutations and patches.

### CODE REVIEW

**Comment by rexxars** [comment]
I assume the index file wasn't intended to be included?

**Comment by kmelve** [comment]
🤦

**Comment by PetterRuud** [comment]
Couldnt people who need the full client just install it individually or?
The full client will add 20x size and 6 more depencies to the bundle, wouldnt it? And Webpack  5 (beta in Next) conflicts with terser 4.

Thanks for answers.

**Comment by rexxars** [comment]
> Couldn't people who need the full client just install it individually or?

They could. I'm not sure if it's very discoverable, though.


> The full client is 300kb and pico is 13kb.

Where are you seeing these numbers? picosanity should be about 1.9kB minified, @sanity/client about 64.

> And Webpack 5 (feature flagged in Next) conflicts with terser 4.

Conflicts how?

**Comment by rexxars** [comment]
We should try to improve the examples in the readme to account for this: if you instantiate the client in a file that is only imported to do `getServerSideProps()`/`getStaticProps()`, it will be removed from the client bundle.

In this scenario the size of the client only comes into play if you're doing client-side requests against Sanity.

**Comment by PetterRuud** [comment]
> > Couldn't people who need the full client just install it individually or?
> 
> They could. I'm not sure if it's very discoverable, though.
> 
> > The full client is 300kb and pico is 13kb.
> 
> Where are you seeing these numbers? picosanity should be about 1.9kB minified, @sanity/client about 64.
> 

It is the unpacked size.

> > And Webpack 5 (feature flagged in Next) conflicts with terser 4.
> 
> Conflicts how?

When i run yarn install --production in my monorepo (webpack5 project and Sanity studio) i get an error when building Sanity studio in Docker.


Would be nice with treeshaking of the client.

**Review by rexxars — APPROVED** [review]

**Pull request merged**
